### PR TITLE
2519 app avatar.js should be broken up to better separate concerns

### LINKED ISSUE #2519: App: Avatar.js should be broken up to better separate concerns
Avatars file is huge, want to clean it up to make implementing an animation state system more manageable.

- move classes to their own files
- move related configs to new class files
- move _applyAnimation and related animation code into a separate file so animation refactoring can be continued while master continues to be updated(this file will be changed/removed in future updates)
- move animation functions into variables for readability, rather than defining them in an if/else block

### PR DESCRIPTION
**Pull request by 0reo**
closes #2519

### CODE REVIEW

**Comment by 0reo** [comment]
This branch currently address the first 3 points of #2519, specifically
- move classes to their own files
- move related configs to new class files
- move _applyAnimation and related animation code into a separate file so animation refactoring can be continued while master continues to be updated(this file will be changed/removed in future updates)

The remain task is
- move animation functions into variables for readability, rather than defining them in an if/else block

I'm going to start that in another branch, but can easily add it to this one if we want.

Also, for clarification, this is an intermediary step towards a cleaner animation system, more code will be changed/removed from avatar.js, and animationHelper.js will be reduced/replaced with more formal animation and state classes in upcoming tickets.

**Comment by amnaarshed4224** [comment]
Issues:
1-Unable to fly. This error pops up.

crashwhile flying

2-"E" activator crashes the app too and throws this error. This way we are unable to equip avatars, items etc.
errwhile trying to change avatar or equip items


https://user-images.githubusercontent.com/35926530/157268130-ae4bef25-f562-4083-8c34-400b7f88d647.mp4

**Comment by 0reo** [comment]
corrected the issues with cubicBezier & localQuaternion which was preventing flight and "E" activator from working

File: avatars/avatars.js [hunk 1]
```diff
@@ -3062,13 +1517,12 @@ class Avatar {
...
       }
     };
-    _updateEyeTarget();
 
     const _updateEyeballTarget = () => {
       const leftEye = this.modelBoneOutputs['Eye_L'];
       const rightEye = this.modelBoneOutputs['Eye_R'];
 
-      const lookerEyeballTarget = this.looker.update(now);
+      const lookerEyeballTarget = this.looker.update(now, this);
```
Comment (avaer) [inline avatars/avatars.js:1525]: If `this` is needed every frame, why not pass it in the constructor?

File: avatars/avatars.js [hunk 2]
```diff
@@ -3083,14 +1537,14 @@ class Avatar {
           const headPosition = eyePosition;
 
           // Look at direction in world coordinate
-          const lookAtDir = localVector2.copy(headPosition).sub(position).normalize();
-      
+          const lookAtDir = this.localVector2.copy(headPosition).sub(position).normalize();
```
Comment (avaer) [inline avatars/avatars.js:1540]: Why make all cache variables local to `this`?

File: avatars/avatars.js [hunk 3]
```diff
@@ -3328,13 +1762,129 @@ class Avatar {
...
+    
+    this.options.visemes && _updateVisemes();
     _updateSubAvatars();
 
     if (metaversefile.isDebugMode() && !this.debugMesh) {
       this.debugMesh = _makeDebugMesh();
       this.debugMesh.wrapToAvatar(this);
       this.model.add(this.debugMesh);
     }
+    //redundant?
```
Comment (avaer) [inline avatars/avatars.js:1887]: It's not redundant, but probably dead code.

**Review by avaer — CHANGES_REQUESTED** [review]
Some `this` issues.

File: avatars/avatars.js (hunk 3 above)
Comment (0reo) [reply avatars/avatars.js:1887]: yes, i wrote that while digging through things and just forgot to remove.  will remove in the update

File: avatars/avatars.js (hunk 2 above)
Comment (0reo) [reply avatars/avatars.js:1540]: i made the local* variables avatar was using members of the avatar class, rather than defined outside of the class

File: avatars/avatars.js (hunk 1 above)
Comment (0reo) [reply avatars/avatars.js:1525]: that does make more sense, will adjust

File: avatars/avatars.js (hunk 3 above)
Comment (0reo) [reply avatars/avatars.js]: this comment has been removed

**Comment by alisaad673** [comment]
Seems to work fine now. No new errors.

File: avatars/avatars.js (hunk 2 above)
Comment (avaer) [reply avatars/avatars.js]: Yeah, IMO we do not need extras. If the implementation is polluting side effects across instances, that's probably a variable collision bug.

Otherwise this is only a waste of memory.

**Review by avaer — APPROVED** [review]

**Comment by avaer** [comment]
This PR regressed the avatars code quality quite a bit by introducing new global variables and the elimination of most idempotency in the code.

Might need to revert this.
