### PR TITLE
Fix avatar img

### LINKED ISSUE #220: Incorrect in-world profile picture
diffprofilepic

### PR DESCRIPTION
**Pull request by chrislatorres**
Fixes #220 
avatarimg

### CODE REVIEW

File: rig.js [hunk 1]
```diff
@@ -127,6 +127,30 @@ class RigManager {
...
+    };
+    const texture = new THREE.Texture(img);
+    const material = new THREE.MeshBasicMaterial({
+      map: texture,
+      side: THREE.DoubleSide,
+    });
+    const avatarMesh = new THREE.Mesh(geometry, material);
+    avatarMesh.position.x = -0.5;
+    avatarMesh.position.y = -0.02;
+    this.localRig.textMesh.add(avatarMesh);
```
Comment (avaer) [inline rig.js:149]: I suspect this will "paper over" the existing avatar mesh without removing it, and additional sets will further add more icons.

https://github.com/webaverse/app/blob/fbb507c4d0e2cc10cf3ef2251dabacf084c34b54/rig.js#L39

It probably makes sense to remove that icon rather than add ones on top.

File: rig.js [hunk 2]
```diff
@@ -127,6 +127,30 @@ class RigManager {
...
+
+    this.localRig.textMesh.sync();
```
Comment (avaer) [inline rig.js:151]: If we aren't changing the text mesh, there is no need to sync.

**Review by avaer — COMMENTED** [review]
This looks functionally correct, but it might not be removing old avatar images.

File: rig.js (hunk 2 above)
Comment (chrislatorres) [reply rig.js]: 1a301bc

File: rig.js (hunk 1 above)
Comment (chrislatorres) [reply rig.js]: 1a301bc

File: rig.js [hunk 3]
```diff
@@ -127,6 +127,30 @@ class RigManager {
...
+    const texture = new THREE.Texture(img);
+    const material = new THREE.MeshBasicMaterial({
+      map: texture,
+      side: THREE.DoubleSide,
+    });
+    const avatarMesh = new THREE.Mesh(geometry, material);
+    avatarMesh.position.x = -0.5;
+    avatarMesh.position.y = -0.02;
+
+    this.localRig.textMesh.remove(this.localRig.textMesh.children[0]);
```
Comment (avaer) [inline rig.js:150]: I would be careful about depending on child order.

The way I usually do it is like `this.localRig.textMesh.avatarMesh = avatarMesh` and then it's by name.

Comment (avaer) [reply rig.js:150]: Otherwise adding a child in a different order will explode this, which would be very surprising.

**Review by avaer — COMMENTED** [review]
One small futureproofing and then it looks good.

File: rig.js (hunk 3 above)
Comment (chrislatorres) [reply rig.js]: 6d0860a and 537c46e

**Review by avaer — APPROVED** [review]
LGTM
