### PR TITLE
Avatar fix for new vrm model

### LINKED ISSUE #1784: App: non-standard optional bone configuration avatars not working
Testing with METATRAVELLER avatars results in the equip issue we have encountered with #1744 and #1521 where it resets to origin and does not equip. 

I have advised their team on VRM practices, but even with a VRM I've made using their data (rigged model, vrm valid) the error still occurs, so I think there's something on our end that's not working - I suspect it's the fact that the model's rig doesn't contain Little Finger bones: 
image

Note - these are considered optional bones in VRM spec. 

The following error occurs on equip: 
image

notably: 
image

Ahad or myself have the test VRM, since it is a non-released project I won't share the data here directly.

### PR DESCRIPTION
**Pull request by skaljac**
Resolve #1784 

Issue:
https://github.com/webaverse/app/issues/1784

### CODE REVIEW

File: avatars/avatars.js [hunk 1]
```diff
@@ -1206,8 +1206,8 @@ class Avatar {
     this.shoulderWidth = modelBones.Left_arm.getWorldPosition(new THREE.Vector3()).distanceTo(modelBones.Right_arm.getWorldPosition(new THREE.Vector3()));
     this.leftArmLength = this.shoulderTransforms.leftArm.armLength;
     this.rightArmLength = this.shoulderTransforms.rightArm.armLength;
-    let indexDistance = modelBones.Left_indexFinger1 ? modelBones.Left_indexFinger1.getWorldPosition(new THREE.Vector3()).distanceTo(modelBones.Left_wrist.getWorldPosition(new THREE.Vector3())) : 0;
-    let handWidth = modelBones.Left_indexFinger1 ? modelBones.Left_indexFinger1.getWorldPosition(new THREE.Vector3()).distanceTo(modelBones.Left_littleFinger1.getWorldPosition(new THREE.Vector3())) : 0;
+    let indexDistance = modelBones.Left_indexFinger1 && modelBones.Left_wrist? modelBones.Left_indexFinger1.getWorldPosition(new THREE.Vector3()).distanceTo(modelBones.Left_wrist.getWorldPosition(new THREE.Vector3())) : 0;
```
Comment (avaer) [inline avatars/avatars.js:1209]: Is it even valid to have an avatar with no wrist bone?

Comment (Vianvolaeus) [reply avatars/avatars.js:1209]: No. 

https://github.com/vrm-c/vrm-specification/tree/master/specification/0.0#vrm-extension-models-bone-mapping-jsonextensionsvrmhumanoid

**Review by avaer — CHANGES_REQUESTED** [review]
Needs wrist code cleanup.

**Review by avaer — APPROVED** [review]
